apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfklease.name" . }}
  labels:
    {{- include "kfklease.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kfklease.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
